spring:
  profiles: dev
  servlet:
    multipart:
      max-file-size: 10Mb
  http:
    multipart:
      max-request-size: 100Mb
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .jsp
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aliexpress?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
server:
  port: 8077